service: aws-nodejs
provider:
  name: aws
  runtime: nodejs12.x
functions:
  createUser:
    handler: handler.createUser
    events:
      -
        http:
          path: users
          method: post
          cors: true
  getOneTime:
    handler: handler.getOneTime
    events:
      -
        http:
          path: 'times/{id}'
          method: get
          cors: true
  getOneUser:
    handler: handler.getOneUser
    events:
      -
        http:
          path: 'users/{id}'
          method: get
          cors: true
  getAllTimes:
    handler: handler.getAllTimes
    events:
      -
        http:
          path: times
          method: get
          cors: true
  getAllUsers:
    handler: handler.getAllUsers
    events:
      -
        http:
          path: users
          method: get
          cors: true
  updateUser:
    handler: handler.updateUser
    events:
      -
        http:
          path: 'users/{id}'
          method: put
          cors: true
  deleteUser:
    handler: handler.deleteUser
    events:
      -
        http:
          path: 'users/{id}'
          method: delete
          cors: true